### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by linghuichen** [OATML-Markslab/ProteinNPT#1]
Thanks for sharing the code of this excellent work. 
Could you provide some specific guidance on how to use this code to replicate the results in the paper?

**Comment by pascalnotin** [comment]
Hi @linghuichen -- the current codebase was meant to provide further details on the inner workings of ProteinNPT. We are working on cleaning up the training code to reproduce all results in the paper. We will push an update as soon as ready!
Best,
Pascal

**Comment by pascalnotin** [comment]
Hi @linghuichen and @jxzly,
I just pushed an upgrade with code, data and instructions to train all models discussed in our paper. Please let me know if any questions.
Best,
Pascal

**Comment by pascalnotin** [comment]
Hi @linghuichen,
Closing this issue as I believe the above addresses your original question. Feel free to re-open the issue if you have any follow up questions.
Kind regards,
Pascal
