### ISSUE TITLE
num_MSA_sequences

### ISSUE THREAD

**Issue by ZhummCrow** [OATML-Markslab/ProteinNPT#14]
Does num_MSA_sequences affect the final result? I retrained proteinnpt on assay IF1_ECOLI_Kelsic_2016 with msat, but got spearman 0.614.

**Comment by pascalnotin** [comment]
Hi @ZhummCrow -- num_MSA_sequences (default [384](https://github.com/OATML-Markslab/ProteinNPT/blob/master/scripts/embeddings_subs.sh#L10)) will have an impact on the embeddings obtained for each sequence -- it corresponds to the number of sequence sampled from the MSA that is input in MSA Transformer. We use the default MSA Transformer hyperparameter values here. If not running into GPU mem bottlenecks, you may be able to get higher performance by increasing that value to a larger value. 
Also note that the final performance you obtain (eg., 0.614 spearman) will vary significantly dependently depending on the particular cross validation scheme you are looking at (eg., random, modulo, contiguous).
Best,
Pascal

**Comment by pascalnotin** [comment]
Ho @ZhummCrow -- closing this issue as I believe the above addressed your question. Feel free to re-open as needed.
Kind regards,
Pascal
