### ISSUE TITLE
How can I reproduce the paper results?

### ISSUE THREAD

**Issue by jxzly** [OATML-Markslab/ProteinNPT#2]
May you share your training code?

**Comment by pascalnotin** [comment]
Dear Jixian - we are working on cleaning up the training code to reproduce all results in the paper and will push an update as soon as ready. I'm closing your issue since it is a duplicate of this [other issue](https://github.com/OATML-Markslab/ProteinNPT/issues/1).
Kind regards,
Pascal

**Comment by jxzly** [comment]
ok, I am looking forward to it.
