### ISSUE TITLE
unable to run embeddings_sub.sh

### ISSUE THREAD

**Issue by adalisan** [OATML-Markslab/ProteinNPT#3]
After following the instructions in the readme to set up the conda env, I tried running embeddings_sub.sh
I get the following ImportError

```
Traceback (most recent call last):
  File "/hpc/ProteinGym/ProteinNPT/scripts/embeddings.py", line 16, in <module>
    from utils import tranception
  File "/hpc/conda/envs/proteinnpt_env/lib/python3.10/site-packages/proteinnpt-1.0-py3.10.egg/utils/__init__.py", line 1, in <module>
ImportError: cannot import name 'esm' from partially initialized module 'utils' (most likely due to a circular import) (/hpc/conda/envs/proteinnpt_env/lib/python3.10/site-packages/proteinnpt-1.0-py3.10.egg/utils/__init__.py)
```

**Comment by pascalnotin** [comment]
Dear Sancar,
Thank you for flagging! A quick fix would be to install the ProteinNPT package in editable mode, ie. replace [this line](https://github.com/OATML-Markslab/ProteinNPT/blob/master/scripts/setup.sh#L8) by: 
`pip install -e $proteinnpt_repo_path/.`
Will work on a more permanent fix soon. 
Kind regards,
Pascal

**Comment by pascalnotin** [comment]
Dear Sancar,

I refactored the code and uploaded proteinnpt to [Pypi](https://pypi.org/project/proteinnpt/). The proteinnpt package is now part of the updated [conda environment](https://github.com/OATML-Markslab/ProteinNPT/blob/master/proteinnpt_env.yml#L26) . We are now also providing a [requirements.txt](https://github.com/OATML-Markslab/ProteinNPT/blob/master/requirements.txt) file if python venv are preferable. 
This should fully address the issue you had raised.

Kind regards,
Pascal

**Comment by pascalnotin** [comment]
@adalisan,
Closing this issue as I believe the above addressed the issue. Feel free to re-open the issue if you have any follow up questions.
Kind regards,
Pascal
