### ISSUE TITLE
How to perform a mutation scan? 

### ISSUE THREAD

**Issue by PKU-Leroy** [OATML-Markslab/ProteinNPT#4]
Could you please give me some guidance if I want to perform a mutation scan on a new protein sequence?

**Comment by pascalnotin** [comment]
Dear Ke-Wei,

The easiest way to score new mutation scans with the current codebase would be to create a new reference file similar to the ones we provide for [ProteinGym](https://github.com/OATML-Markslab/ProteinNPT/blob/master/utils/proteingym/DMS_substitutions.csv), and include the information relative to your new assay(s). For everything to run properly you will just have to include the following values:
- DMS_id: A unique identifier of your choosing for the assay 
- DMS_filename: The name of the csv containing all mutants for your analysis, and the available experimental measurements. We provide several examples of such files as part of the data downloadable from our repo (eg., all files under `data/fitness/substitutions_singles` in the [zip file](https://github.com/OATML-Markslab/ProteinNPT/blob/master/README.md?plain=1#L14-L15)). Key columns are "mutant" (triplet identifying the mutation), "mutated_sequence" (full amino acid sequence), "DMS_score" (experimental measurement) and a fold variable. If you just want to train on a subset of mutants, and test on the rest, you could create a fold variable with a name of your choosing (say "fold_train_test"), set all training instances to 0, all test instances to 1. When running the code, make sure you set [test_fold_index](https://github.com/OATML-Markslab/ProteinNPT/blob/master/scripts/train.py#L306) to 1, [assay_location(https://github.com/OATML-Markslab/ProteinNPT/blob/master/scripts/train.py#L300) to the path of the folder where your assay csv file is stored, and [fold_variable_name](https://github.com/OATML-Markslab/ProteinNPT/blob/master/scripts/train.py#L305) to "fold_train_test"
- UniProt_ID: Only used for reporting purposes. This could be set to any text string you want, eg. the same as DMS_id
- target_seq: The full wild type sequence used in the mutational scan
- seq_len: Length of that wild type sequence
- MSA_filename: filename of the MSA used to obtained MSA Transformer embeddings. This file should be stored in the [MSA_data_folder](https://github.com/OATML-Markslab/ProteinNPT/blob/master/scripts/embeddings.py#L116) path.
- MSA_start, MSA_end, MSA_len: in the standard case, the MSA is done over the full sequence length, and thus MSA_start=1, MSA_end=MSA_len=seq_len. If the MSA is done for a subdomain, MSA_start is the position of the first AA in the wild type sequence covered by the MSA, MSA_end the position of the last AA covered by the MSA (note positions are 1-indexed by convention)
- weight_file_name: file that contains weights for sequences in the MSA. You may use the [weights computation function(https://github.com/OATML-Markslab/ProteinNPT/blob/master/utils/msa_utils.py#L155-L167) in the MSA processing class for this. For more details, please refer to the supplementary material of the [EVE paper](https://www.nature.com/articles/s41586-021-04043-8), paragraph 3.2.1

Please let me know if any questions. 

Kind regards,
Pascal

**Comment by pascalnotin** [comment]
Hi @PKU-Leroy,

I just pushed a [pipeline script](https://github.com/OATML-Markslab/ProteinNPT/blob/master/scripts/pipeline.py) and added instructions to the README [here](https://github.com/OATML-Markslab/ProteinNPT/blob/master/README.md?plain=1#L59-L64) to facilitate the end-to-end training process as described above. Things should be much simpler to use now!
Closing this issue as I believe this is now fully addressed, but feel free to re-open if any further questions on the above.

Best,
Pascal

**Comment by PKU-Leroy** [comment]
Many thanks, Pascal. I will try this script soon and I am deeply appreciative of your patient guidance.



---- Replied Message ----
| From | Pascal ***@***.***> |
| Date | 02/29/2024 05:41 |
| To | ***@***.***> |
| Cc | Ke-Wei ***@***.***>***@***.***> |
| Subject | Re: [OATML-Markslab/ProteinNPT] How to perform a mutation scan? (Issue #4) |

Hi @PKU-Leroy,

I just pushed a pipeline script and added instructions to the README here to facilitate the end-to-end training process as described above. Things should be much simpler to use now!
Closing this issue as I believe this is now fully addressed, but feel free to re-open if any further questions on the above.

Best,
Pascal
