### ISSUE TITLE
MSA processing error

### ISSUE THREAD

**Issue by dc2211** [OATML-Markslab/ProteinNPT#6]
Hello, 

first of all, thank you so much for this amazing work!

Im trying to follow the pipeline.sh script with my own DMS data, but Im getting the following error in the MSA processing

```
Computing MSA sequence weights
Proportion of sequences dropped due to fraction of gaps: 33.33%
Proportion of non-focus columns removed: 0.0%
Traceback (most recent call last):
  File "/home/projects/ProteinNPT/scripts/pipeline.py", line 98, in <module>
    _ = MSA_processing(
        ^^^^^^^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/proteinnpt/utils/msa_utils.py", line 57, in __init__
    self.gen_alignment()
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/proteinnpt/utils/msa_utils.py", line 114, in gen_alignment
    start,stop = focus_loc.split("-")
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

Not sure if the issue comes from the format of the MSA file. At the moment, Im using an MSA in a3m format (which looks as a fasta alignment).

Many thanks!

**Comment by pascalnotin** [comment]
Hi @elevhen,

Thank you for the kind words! 

So far we have only used .a2m MSAs obtained with the [EVcouplings pipeline](https://github.com/debbiemarkslab/EVcouplings) -- see for examples the MSAs we provide via the ProteinGym repo [here](https://github.com/OATML-Markslab/ProteinGym/blob/main/README.md?plain=1#L94). I just added that clarification on the README. There are tools to convert a3m to a2m -- for example with [reformat.pl](https://github.com/soedinglab/hh-suite/blob/master/scripts/reformat.pl) from the hh-suite. 

Additionally, the [MSA_processing](https://github.com/OATML-Markslab/ProteinNPT/blob/master/proteinnpt/utils/msa_utils.py#L14) class was expecting the first line in the MSA to include the index of the first and last amino acid for the alignment (both with respect to the full wild type sequence coordinate system) -- this is added by default in the MSAs we get with EVcouplings. For instance, for BRCA1_HUMAN, the first line of our MSA is ">BRCA1_HUMAN/1-1863". However, the few lines that were making use of that information were legacy code / were not effectively used anywhere else. I just removed these lines in the last commit, so hopefully the error goes away with that update. 

Best,
Pascal

**Comment by elevhen** [comment]
Hi Pascal,

thanks for your prompt response! The problem that I had before got solved, but now I see that the pipeline is complaining on the embedding processing, with a runtime error on the MSA seq length, where should be equal. I have double check my new a2m MSA and everything looks in order (all sequences are in the same length, with or without gaps). 

```
MSA start and end not provided -- Assuming the MSA is covering the full WT sequence
Assay: test_DMS.csv
Proportion of sequences dropped due to fraction of gaps: 0.0%
Proportion of non-focus columns removed: 0.0%
Encoding sequences
One-hot encoded sequences shape:(63, 539, 20)
Loaded sequence weights from disk
Neff = 58.33333333333333
Data Shape = (63, 539, 20)
Neff: 58.33333333333333
Name of focus_seq: >5980390
Check sum weights MSA: 52.83333333333333
  0%|                                                                                                                                    | 0/108 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/projects/ProteinNPT/scripts/embeddings.py", line 284, in <module>
    processed_batch = process_embeddings_batch(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/ProteinNPT/scripts/embeddings.py", line 87, in process_embeddings_batch
    batch_sequence_names, batch_AA_sequences, batch_token_sequences = token_batch_converter(batch['mutant_mutated_seq_pairs'])    
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/proteinnpt/utils/esm/data.py", line 327, in __call__
    raise RuntimeError(
RuntimeError: Received unaligned sequences for input to MSA, all sequence lengths must be equal.
```

I double checked that both the sequences in the MSA (including gaps) and DMS data just to be aware that all the sequences were the same length (539 in this case). 

Many thanks again for all your help again!

**Comment by pascalnotin** [comment]
Hi @elevhen - good to hear for the first bug! 

Regarding the second bug, the function triggering the error ([token_batch_converter = alphabet.get_batch_converter()](https://github.com/OATML-Markslab/ProteinNPT/blob/master/proteinnpt/proteinnpt/data_processing.py#L182-L183)) is borrowed from the [ESM codebase](https://github.com/facebookresearch/esm/blob/main/esm/data.py#L136) to interface w/ MSA Transformer. It internally calls [MSABatchConverter](https://github.com/facebookresearch/esm/blob/main/esm/data.py#L300) -- which complains about sequences in the MSA not being same length.

If you print values for `batch['mutant_mutated_seq_pairs']`, are all sequences the same length as well?

Best,
Pascal

**Comment by elevhen** [comment]
Hi Pascal, 

thanks again for all the help. Unfortunately, it seems if not going beyond mutant_0, so it only prints that one and then it crashes. Any recommendations?

```
Encoding sequences
One-hot encoded sequences shape:(63, 539, 20)
Loaded sequence weights from disk
Neff = 58.33333333333333
Data Shape = (63, 539, 20)
Neff: 58.33333333333333
Name of focus_seq: >5980390
Check sum weights MSA: 52.83333333333333
  0%|                                                                                                                                    | 0/108 [00:00<?, ?it/s]
[['mutant_0', 'MLSPKGMEDSNSISYNKEAIEPDQGVKIITHKECNTIGINGMLFNSIQVRLPLLLILSLIPKIKAVQSVQSSVGNLITTSTVDKYDIYDLVAIKSVQDYVNKEIVPSIARLGCEAAGLQLGIALTQHYSELTNIFGDNIGSLQEKGIKLQGIASLYRTNITRVIDVDLEIFLFTIQNREWYIPLPSHIMTKGAFLGGADVKECIEAFSSYICPSDPGFVLNHEMESCLSGNISQCPRTTVTSDIVPRYAFVNGGVVANCITTTCTCNGIGNRINQPTNKEGIVNDLNTQIYKTRLNFETRYVDSDLEESKEWIRRSNQKLDSIGSWHQSSTTIIIILIMMIILFIINITIITIAIKYYRIQKRNRVDQNDKPYVLSILSIITTMIMASHCQIDITLVNTLAFYTPDDITKLQRDTNKISQYSITLLNNSVALDPIDISIELNKAKSCGDQQIKQYKRLLDRLIIPLYDGLKLQKDVIVTNQESNENTDPRTERFFGGVIGTIALGVATSAQITAAVALVEAKQPKHVGVKTNKSDIEKL']]
  0%|                                                                                                                                    | 0/108 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/projects/ProteinNPT/scripts/embeddings.py", line 285, in <module>
    processed_batch = process_embeddings_batch(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/ProteinNPT/scripts/embeddings.py", line 87, in process_embeddings_batch
    batch_sequence_names, batch_AA_sequences, batch_token_sequences = token_batch_converter(batch['mutant_mutated_seq_pairs'])    
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/proteinnpt/utils/esm/data.py", line 327, in __call__
    raise RuntimeError(
RuntimeError: Received unaligned sequences for input to MSA, all sequence lengths must be equal.
```

Many thanks!

**Comment by elevhen** [comment]
Hi again Pascal, 

please dismiss the last message. I managed to print the whole values for `batch['mutant_mutated_seq_pairs']`. I see 2 lists:

- one that contains the parent sequence in the format `[['mutant_0', 'seq']]`
- another that contains the first 61 residues of mutant_0 and all the MSA sequences in the format `[[('mutant_0', 'seq[:61]'), ('>WT', 'seq'), ('>MSA_seq_1', 'seq') ... ('>MSA_seq_n', 'seq')]]`

Not sure why the first term of the second list only considers the first 61 aminoacids of the WT, and it seems that it the source of the error, since that is the only one that does not have the same length. All the rest MSA sequences have the same length (including gaps).

Hope this helps to clarify any potential source of error. Many thanks again!

**Comment by pascalnotin** [comment]
Hi @elevhen -- thanks for the additional info! Is your DMS assay a .csv file with at least mutated_sequence and DMS_score as two separate columns (and one protein sequence per row)? Since the first sequence is cut at 60 (a standard width delimiter for FASTA files), I'm wondering if your input assay is in FASTA format instead?

**Comment by elevhen** [comment]
Hi Pascal, to be honest I though exactly the same and I double check if there was any line break in the file, or if I made a mistake and was giving a fasta input, but no. Actually, the fasta file that Im using as target_seq has the sequence in one line, no breaks. 

The CSV I was using for `assay_data_location` has the `mutated_sequences` and `DMS_score` columns, with one full sequence per line and the corresponding score. After running pipeline.sh, it modifies the file and adds both the `mutant` and `fold_random_5 columns`, which I think is ok. I re-wrote the CSV file now, and it seems the problem "disappeared" (so there was something wrong in it). Unfortunately, Im having another error now :(

```
Training ProteinNPT model on the TEST_DMS2 assay
fold_variable_name not found in assay file. Assigning 5 folds at random
Mutated region not found from 'mutant' variable -- assuming the full protein sequence is mutated
fold_random_5
3    28
1    26
0    21
2    17
4    16
Name: count, dtype: int64
####################################################################################################
Step1: Computing sequence embeddings for the TEST_DMS2 assay
####################################################################################################
MSA start and end not provided -- Assuming the MSA is covering the full WT sequence
Assay: TEST_DMS2.csv
Proportion of sequences dropped due to fraction of gaps: 0.0%
Proportion of non-focus columns removed: 0.0%
Encoding sequences
One-hot encoded sequences shape:(63, 539, 20)
Loaded sequence weights from disk
Traceback (most recent call last):
  File "/home/projects/ProteinNPT/scripts/embeddings.py", line 187, in <module>
    MSA_sequences, MSA_weights = process_MSA(args, MSA_filename, MSA_weights_filename)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/proteinnpt/utils/msa_utils.py", line 255, in process_MSA
    MSA_all_sequences, MSA_non_ref_sequences_weights = compute_sequence_weights(MSA_filename = filtered_MSA_filename, MSA_weights_filename = args.MSA_weight_data_folder + os.sep + MSA_weights_filename)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/proteinnpt/utils/msa_utils.py", line 211, in compute_sequence_weights
    processed_MSA = MSA_processing(
                    ^^^^^^^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/proteinnpt/utils/msa_utils.py", line 57, in __init__
    self.gen_alignment()
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/proteinnpt/utils/msa_utils.py", line 160, in gen_alignment
    self.seq_name_to_weight[seq_name]=self.weights[i]
                                      ~~~~~~~~~~~~^^^
IndexError: index 36 is out of bounds for axis 0 with size 36
```

Excuse me for all this back and forth. Im confident we will find a solution! Many thanks for your help!

**Comment by pascalnotin** [comment]
No worries! It is very helpful for us to understand which issue arise in practice outside of the assays / MSAs we have put together ourselves. 
I suspect the existing weight file might have been computed with the earlier MSA file and, since we do not recompute weights if the file is already on disk, the best thing might be to delete the current one (should be located in `$DATA_PATH/data/MSA/MSA_weights`) and restart the pipeline script from scratch.
We have also been working on enhancements to weights computation which we will push shortly.

**Comment by elevhen** [comment]
Hi Pascal, thanks again for the support. Just tried removing all the TEST_DMS*.npy files as you suggested and I keep getting the same error.

**Comment by pascalnotin** [comment]
Ok thank you! Will circle back with you once we have pushed the new version of weights computation. Hopefully that resolves that issue. Should be pushed by tomorrow.

**Comment by elevhen** [comment]
sounds great, thank you so much for the help. Looking forward!

**Comment by pascalnotin** [comment]
Hi @elevhen - confirming we have pushed the new weights computation logic in. Please let us know if the issue persists at your end and we will look into it.

**Comment by elevhen** [comment]
Hi Pascal, thanks for this. Im getting the following error now. I assume is a missing variable, that I do not see define in the config.sh, or anywhere else. Might be something that got there that it was being used before? As expected, Im just defining the locations of the DMS data, MSA, and target sequence (fasta). Thanks for all the help!

```
Traceback (most recent call last):
  File "/home/projects/ProteinNPT/scripts/pipeline.py", line 140, in <module>
    run_embeddings(
  File "/home/projects/ProteinNPT/scripts/embeddings.py", line 230, in main
    MSA_sequences, MSA_weights = process_MSA(MSA_data_folder=MSA_data_folder, MSA_weight_data_folder=MSA_weight_data_folder, MSA_filename=MSA_filename, MSA_weights_filename=MSA_weights_filename, path_to_hhfilter=path_to_hhfilter)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: process_MSA() got an unexpected keyword argument 'MSA_data_folder'
```

**Comment by elevhen** [comment]
just to add on top of the last comment, I double check that the MSA_location is properly defined, and that MSA_location and MSA_data_folder are defined just before being called by the process_MSA function. Everything looks in order, and I see the right location. Also, the argument in the process_MSA function is properly placed. 

Any other ideas? Thanks again, Pascal.

**Comment by loodvn** [comment]
Hi @elevhen, you're right that MSA_data_folder is a new argument in process_MSA (it used to take `args` as an input, see [the previous code](https://github.com/OATML-Markslab/ProteinNPT/blame/a932bb45405e0ef9973a94bb405409982a143ee3/proteinnpt/utils/msa_utils.py#L250).

I think I've had a similar error because of the package not refreshing. So basically, the pipeline.py code is calling the `process_MSA` function in the previously installed proteinnpt via pip, instead of the newest version of the code.

Could you try running `pip install -e .` from the root of your repo? Then any new changes within the proteinnpt/ source code should work (hopefully).

**Comment by elevhen** [comment]
Hi Pascal, thanks again. That solved the issue with `MSA_data_folder`, but I got back to the` RuntimeError: Received unaligned sequences for input to MSA, all sequence lengths must be equal.`

```
Embedding sequences:   0%|                                                                                                               | 0/108 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/projects/ProteinNPT/scripts/pipeline.py", line 140, in <module>
    run_embeddings(
  File "/home/projects/ProteinNPT/scripts/embeddings.py", line 331, in main
    processed_batch = process_embeddings_batch(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/ProteinNPT/scripts/embeddings.py", line 123, in process_embeddings_batch
    batch_sequence_names, batch_AA_sequences, batch_token_sequences = token_batch_converter(batch['mutant_mutated_seq_pairs'])    
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/ProteinNPT/proteinnpt/utils/esm/data.py", line 327, in __call__
    raise RuntimeError(
RuntimeError: Received unaligned sequences for input to MSA, all sequence lengths must be equal.
```

**Comment by loodvn** [comment]
Hi @elevhen - glad to know the previous issue is resolved and we're back to the central issue.

Could you check again what those sequence lengths in your batch are at two places:
At the beginning of the process_embeddings_batch() function, and then again right before the `token_batch_converter` function? Then we might know if the sequences are being padded/sliced incorrectly within the function.

**Comment by elevhen** [comment]
Hi Pascal, here is what I get from those two print():

- At the beginning of the `process_embeddings_batch()` function:

`[[''mutant_0, 'seq']] # here seq is full`

- Right before the `token_batch_converter`:

`[[('mutant_0', 'seq[:61]'), ('>WT', 'seq'), ('>ID_1', 'seq'), ... ('>ID_n', 'seq')]] # mutant_0 sequence is cut at residue 61, while the rest is full and all the same size as WT.`

Hope this helps! Thanks.

**Comment by loodvn** [comment]
Thanks for checking:

> "The rest is full and all the same size as WT"
Some questions:
- I assume that WT is of length 61 then? Or is mutant_0 the only one of length 61? 
- Were all the other sequences (ID_1 -> n) all the same length as WT at the beginning of the `process_embeddings_batch()` function, so weren't changed?

**Comment by loodvn** [comment]
Also, I see this issue disappeared earlier when you re-created the CSV (https://github.com/OATML-Markslab/ProteinNPT/issues/6#issuecomment-1991911379) - is there a way you could try fixing it like that again? 
Because the weights computation code has been updated today so I'm curious to see if the weights error has disappeared then.

**Comment by elevhen** [comment]
Hi @loodvn 

> I assume that WT is of length 61 then? Or is mutant_0 the only one of length 61?

WT is of length 539. mutant_0 is 539 in the output at the beginning of the `process_embeddings_batch()` function, but is sliced to 61 right before the `token_batch_converter`

> Were all the other sequences (ID_1 -> n) all the same length as WT at the beginning of the process_embeddings_batch() function, so weren't changed?

At the beginning of the `process_embeddings_batch()` function I only see mutant_0. When printing right before `token_batch_converter`, all the other sequences (ID_1 -> n) are the same length as WT (including gaps "-")

> Also, I see this issue disappeared earlier when you re-created the CSV (https://github.com/OATML-Markslab/ProteinNPT/issues/6#issuecomment-1991911379) - is there a way you could try fixing it like that again?

Unfortunately, I did try this but it got stuck with the same error.

Hope this helps. Many thanks!

**Comment by elevhen** [comment]
> Unfortunately, I did try this but it got stuck with the same error.


Same error being >> `RuntimeError: Received unaligned sequences for input to MSA, all sequence lengths must be equal.`

**Comment by loodvn** [comment]
This helps a lot, thank you for the quick reply! Very strange - so to confirm, I'm guessing the WT and ID_1 - ID_n are the sampled MSA from line 74 of embedding.py (Pascal might be able to weigh in more here). 

I'm trying to locate at which line within `process_embeddings_batch()` the length changes, and `batch['mutant_mutated_seq_pairs']` gets changed possibly a few times:
- `slice_sequences()`
- `align_new_sequences_to_msa()`

Could you perhaps figure out at which point the mutant's length gets truncated to 61 by putting in a few more checks between those functions that check that all the lengths are equal? Then we can maybe deeper into the function causing the error.

**Comment by loodvn** [comment]
I'm not sure I understand line 106 but it could be a clue ("Have to resort to this otherwise "mutant_to_score" is truncated") - could you check whether you're using `indel_mode` or `fast_MSA_mode`? This will affect which functions are being run.

**Comment by pascalnotin** [comment]
Hi @elevhen - could you please print the lengths of sequences in your batch right before lines 71, 82 and 97 and let us know where the truncation for `mutant_0` first happens?

**Comment by elevhen** [comment]
Hi @pascalnotin  and @loodvn, sorry for the late reply. I think I found the error, based on your suggestions. The outputs are:
 
- line 60: `[['mutant_0', 'seq[full]']]` 
- line 65: `[['mutant_0', 'seq[full]']]`
- line 69: `['mutant_0', 'seq[:61]']`
- line 71: `['mutant_0', 'seq[:61]']`
- line 82: `[('mutant_0', 'seq[:61]'), ('>WT', 'seq'), ('>ID_1', 'seq'), ... ('>ID_n', 'seq')]`
- line 97: `[('mutant_0', 'seq[:61]'), ('>WT', 'seq'), ('>ID_1', 'seq'), ... ('>ID_n', 'seq')]`

If I look the values for MSA_start_index and MSA_end_index, we get

- `MSA_start_index` = 0
- `MSA_end_index` = 61

So, for the moment, I explicitly stated both MSA_start (0) and MSA_end (539) in pipeline.sh, through pipeline.py. That solved the problem! :')
 
Now, another error came up on Step 2:
 
```
Batch sizes: torch.Size([1, 400, 540])
Scoring masked-marginals: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 540/540 [37:18<00:00,  4.15s/it]
Traceback (most recent call last):
  File "/home/projects/ProteinNPT/scripts/zero_shot_fitness_esm.py", line 564, in <module>
    main(args)
  File "/home/projects/ProteinNPT/scripts/zero_shot_fitness_esm.py", line 408, in main
    df[f"{model_location}_seed{seed}"] = df.apply(
                                         ^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/pandas/core/frame.py", line 10361, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/ProteinNPT/scripts/zero_shot_fitness_esm.py", line 409, in <lambda>
    lambda row: label_row(
                ^^^^^^^^^^
  File "/home/projects/ProteinNPT/scripts/zero_shot_fitness_esm.py", line 254, in label_row
    wt, idx, mt = mutation[0], int(mutation[1:-1]) - offset_idx, mutation[-1]
                               ^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'utant_'
Traceback (most recent call last):
  File "/home/projects/ProteinNPT/scripts/pipeline.py", line 260, in <module>
    subprocess.run("python zero_shot_fitness_esm.py "+zero_shot_run_parameters, check=True, shell=True)
  File "/home/conda_envs/proteinnpt_env/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python zero_shot_fitness_esm.py --model-location /home/projects/ProteinNPT/ProteinNPT_data/ESM/MSA_Transformer/esm_msa1b_t12_100M_UR50S.pt                 --model_type MSA_Transformer                 --dms-input /home/projects/ProteinNPT/TEST_DMS.csv                 --dms-output /home/projects/ProteinNPT/ProteinNPT_data/data/zero_shot_fitness_predictions/substitutions/MSA_Transformer                 --scoring-strategy masked-marginals                 --msa-path /home/projects/ProteinNPT/TEST.a2m                 --target_seq /home/projects/ProteinNPT/TEST_WT.fasta                 --msa-weights-folder /home/projects/ProteinNPT/ProteinNPT_data/data/MSA/MSA_weights                 --weight_file_name TEST_DMS_theta_0.2.npy                 --seeds 1 2 3 4 5 --MSA_end 539 ' 
returned non-zero exit status 1.
```

thanks again for all your help!

**Comment by pascalnotin** [comment]
Hi @elevhen -- great regarding the first bug, will look into it more closely later to understand what may have happened there! 

Regarding the second bug, the issue is that zero-shot fitness prediction with MSA Transformer requires true mutant triplets (eg., "A1R" if an alanine is mutated to an arginine at position 1) which you do not have in your assay file (which is why the dummy "mutant_i" variables are created. The fix is to either manually add these mutant triplets to your assay file, or deactivate the zero-shot fitness predictions with MSA Transformer by adding "--deactivate_zero_shot_prediction" as an argument when calling `pipeline.py`. We will add more instructions about this on the README / disable zero-shot when mutant triplets are absent going forward - thank you for flagging!

**Comment by elevhen** [comment]
Hi @pascalnotin, thanks for the quick response. 

> The fix is to either manually add these mutant triplets to your assay file

Any specific column name for these?

I will try both: adding the triplets and adding "--deactivate_zero_shot_prediction" as an argument when calling `pipeline.py`. Keep you posted if everything works well. Many thanks again!

**Comment by elevhen** [comment]
Quick update on adding "--deactivate_zero_shot_prediction" as an argument when calling pipeline.py. It skips step 2, but the error is now related to differences shapes for mask and tensor on data_preprocessing.py. 

```
Proportion of sequences dropped due to fraction of gaps: 0.0%
Proportion of non-focus columns removed: 0.0%
Number of sequences after preprocessing: 36
One-hot encoding sequences
Data Shape = (36, 539, 20)
Loading sequence weights from disk
Neff = 28.0
Number of sequences:  36
Neff: 28.0
Name of focus_seq: >5980390
Check sum weights MSA: 27.5
tmp: Starting training
Model device: cuda:0
  0%|                                                                                                                                  | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/hpc/scratch/nvme1/jc991908/projects/ProteinNPT/scripts/train.py", line 453, in <module>
    main(args)
  File "/hpc/scratch/nvme1/jc991908/projects/ProteinNPT/scripts/train.py", line 293, in main
    trainer_final_status = trainer.train()
                           ^^^^^^^^^^^^^^^
  File "/hpc/scratch/nvme1/jc991908/projects/ProteinNPT/proteinnpt/utils/model_utils.py", line 167, in train
    processed_batch = proteinnpt.proteinnpt.data_processing.process_batch(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/scratch/nvme1/jc991908/projects/ProteinNPT/proteinnpt/proteinnpt/data_processing.py", line 202, in process_batch
    sequence_embeddings[masked_indices] = 0.0
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
IndexError: The shape of the mask [91, 62] at index 1 does not match the shape of the indexed tensor [91, 540, 768] at index 1
```

**Comment by elevhen** [comment]
Quick update on adding "--deactivate_zero_shot_prediction" as an argument when calling `pipeline.py`. It skips step 2, but the error is now related to differences shapes for mask and tensor on `data_preprocessing.py`. 

```
Proportion of sequences dropped due to fraction of gaps: 0.0%
Proportion of non-focus columns removed: 0.0%
Number of sequences after preprocessing: 36
One-hot encoding sequences
Data Shape = (36, 539, 20)
Loading sequence weights from disk
Neff = 28.0
Number of sequences:  36
Neff: 28.0
Name of focus_seq: >5980390
Check sum weights MSA: 27.5
tmp: Starting training
Model device: cuda:0
  0%|                                                                                                                                  | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/projects/ProteinNPT/scripts/train.py", line 453, in <module>
    main(args)
  File "/home/projects/ProteinNPT/scripts/train.py", line 293, in main
    trainer_final_status = trainer.train()
                           ^^^^^^^^^^^^^^^
  File "/home/projects/ProteinNPT/proteinnpt/utils/model_utils.py", line 167, in train
    processed_batch = proteinnpt.proteinnpt.data_processing.process_batch(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/ProteinNPT/proteinnpt/proteinnpt/data_processing.py", line 202, in process_batch
    sequence_embeddings[masked_indices] = 0.0
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
IndexError: The shape of the mask [91, 62] at index 1 does not match the shape of the indexed tensor [91, 540, 768] at index 1
```

**Comment by pascalnotin** [comment]
This is potentially due to the same issue as the original problem you were facing given the size mismatch. Could you please confirm the length of the [`target_seq`](https://github.com/OATML-Markslab/ProteinNPT/blob/master/scripts/pipeline.sh#L13) sequence passed in as argument to `pipeline.py` is of length 539 as well?

**Comment by elevhen** [comment]
you were totally correct. Now training is finally running as it should. Thank you so much for this long and useful journey! I will keep you posted if anything extra appears, but I think we should be fine now.

**Comment by pascalnotin** [comment]
Great to hear! Could you please let me know whether the issue was resolved by fixing the length of the input target_seq parameter or by specifying values for the parameters MSA_start and MSA_end? 
In theory the latter is not necessary if the length of the target_seq is the same as mutated sequences and sequences in the MSA. I would like to make sure there is nothing else in the code we should modify!

**Comment by pascalnotin** [comment]
Regarding the zero-shot fitness computation, the variable name for mutant triplets expected by the code is `mutant`. If this variable was not present in the assay file, we were setting its values to default "mutant_i". In the new version we just pushed (thanks @loodvn for the suggestion), if the variable is not present, we are computing these mutant triplets automatically by comparing target_seq and the various mutated sequences. With that update to the code you should thus be able to leverage zero-shot fitness predictions from MSA Transformer as auxiliary labels within ProteinNPT (you would now need to remove `--deactivate_zero_shot_prediction` from the `pipeline.py` parameters, and use the initial default parameters as per the README file).

**Comment by elevhen** [comment]
Hi @pascalnotin, thanks and sorry for the late reply! Indeed, the mistake was mine in `target_seq`, which lead all the chain of events that happened in this thread (sorry!). 

> In the new version we just pushed

Is this already up?

---
To finalize this thread, and reading issue #8 , I noticed there is a `load_model_checkpoint` argument in `train.py`. I was wondering if it would be enough to use that in order to load the generated checkpoint for inference? Not sure if I'm interpreting #8 correctly, but editing the original DMS.csv file and adding the new sequences for inference there (with index 0), would lead to re-training everything again? I tried that way, and it seems the training started all over. 

The other option I see would be to

1. load seqs for inference
2. embed with ESM (not sure if by default it embeds the sequences with ESM1v (only zero-shot?), ESM1b or a one-hot?)
3. load checkpoint
4. pass embeddings
5. predict 

Does this make sense? 

Thanks again for all the help and learnings through this! Continue with the amazing work!

**Comment by pascalnotin** [comment]
Hi @elevhen -- the latest commit should now be up :)

Regarding inference w/ a trained model, you are correct regarding my proposal to issue [#8](https://github.com/OATML-Markslab/ProteinNPT/issues/8) requiring a retrain. You can definitely handle it via train.py and `load_model_checkpoint`, but it may require you to iterate a bit with other function parameters / making sure you have all embeddings needed in the file the code expects. Note that embeddings used in ProteinNPT are from MSA Transformer, not ESM1b/v.

The codebase we have released so far has been primarily focused on providing everything needed to reproduce the results from the paper. There are several other functionalities we now want to enable as the models are used in other contexts -- loading from checkpoint to perform inference on new mutated sequences is definitely one of them. We will try and push an update supporting that later this week.

**Comment by elevhen** [comment]
thank you so much @pascalnotin ! I think I made it work :) 

Looking forward for the update!

**Comment by loodvn** [comment]
Hi @elevhen! 

Just a heads-up since you've been working with the repository lately: 
We rewrote one of my earlier commit messages because it was popping up everywhere, but we had to rebase and force push to make this change (we'll make sure not to force push like this in the future though!)

So the actual codebase hasn't changed, but you'll just need to do the following commands, which depend on whether you've forked or just cloned the repo.

Scenario 1: If you’ve forked the repo, run each of these commands individually:
```
git fetch --all # Get all the latest remote changes
git checkout master # Checkout your local master branch
git rebase upstream/master  # Assuming upstream is https://github.com/OATML-Markslab/ProteinNPT.git, which you can check using git remote -v
git push --force origin master  # Push these changes to your repo
```
Then if you have different branches, run these commands one-by-one (e.g. if you have a branch named <my_local_branch>:
```
git checkout my_local_branch
git rebase master  # Rebase to match the new history from your local master branch
git push --force origin my_local_branch
```

Scenario 2: If you’ve cloned the ProteinNPT repo locally
```
# In this case you don't need to do force pushes because you're just working locally

git fetch --all
git checkout master
git rebase origin/master  # Assuming origin here is https://github.com/OATML-Markslab/ProteinNPT.git, which you can check using git remote -v
```
Then for each of you local branches:
```
# For each of your branches
git checkout my_local_branch
git rebase master
```

Could you please let me know if this works for you? I'm happy to help with any steps along the way until it's fixed on your end.

**Comment by elevhen** [comment]
Hi @pascalnotin! thanks for the heads up on this. I follow your advice on scenario 2 and it worked just fine :)

Please keep me posted on any new functionalities, specially the one for predicting on new mutant sequences! Thanks again.

**Comment by pascalnotin** [comment]
Hi @dc2211 -- just pushed an eval script [here](https://github.com/OATML-Markslab/ProteinNPT/blob/master/scripts/eval.sh). Let me know if any questions!

**Comment by pascalnotin** [comment]
We pushed a revised version of the proteinnpt package on pypi along with the update yesterday. Please update to v1.4

**Comment by dc2211** [comment]
Thanks for the help. I will close this issue and continue on #12
